/research/dept7/glchen/miniconda3/envs/guojin/bin/python test.py \
--gpu_ids 0 \
--display_winsize 512 \
--preprocess resize_and_crop \
--load_size 512 \
--crop_size 512 \
--dataroot /research/dept7/glchen/datasets/dataset-opc/Binary \
--name dcupp_naive6_50epoch_512 \
--model pix2pix \
--netG dc_unet_nested \
--netD naive6_nl \
--output_nc 1 \
--direction AtoB \
--dataset_mode aligned \
--eval \
--num_test 2170 \
--norm batch
