/research/dept7/wlchen/miniconda3/envs/guojin/bin/python test.py \
--gpu_ids 0 \
--display_winsize 256 \
--preprocess resize_and_crop \
--load_size 512 \
--crop_size 512 \
--dataroot /research/dept7/wlchen/guojin/dataset-opc/Binary \
--name Custom_pix2pix_binary_60epoch_256 \
--model pix2pix \
--netG unet_256 \
--output_nc 1 \
--direction AtoB \
--dataset_mode aligned \
--eval \
--num_test 2170 \
--norm batch
