python3 test.py \
--gpu_ids 0 \
--display_winsize 256 \
--preprocess resize_and_crop \
--load_size 512 \
--crop_size 512 \
--dataroot /cephfs/person/asdfghchen/LithoGAN/data/LithoGAN/Binary \
--name LithoGAN_pix2pix_binary_200epoch_512 \
--model pix2pix \
--netG unet_256 \
--output_nc 1 \
--direction AtoB \
--dataset_mode aligned \
--eval \
--num_test 2170 \
--norm batch
